export type AssetType = 'Stock' | 'ETF' | 'Futures' | 'Crypto' | 'Forex'

export interface SymbolEntry {
  symbol: string
  name: string
  type: AssetType
}

export const SYMBOLS: SymbolEntry[] = [
  // ── Popular US Stocks ──
  { symbol: 'AAPL',  name: 'Apple Inc.',                          type: 'Stock' },
  { symbol: 'MSFT',  name: 'Microsoft Corp.',                     type: 'Stock' },
  { symbol: 'NVDA',  name: 'NVIDIA Corp.',                        type: 'Stock' },
  { symbol: 'AMZN',  name: 'Amazon.com Inc.',                     type: 'Stock' },
  { symbol: 'GOOGL', name: 'Alphabet Inc. (Class A)',             type: 'Stock' },
  { symbol: 'GOOG',  name: 'Alphabet Inc. (Class C)',             type: 'Stock' },
  { symbol: 'META',  name: 'Meta Platforms Inc.',                 type: 'Stock' },
  { symbol: 'TSLA',  name: 'Tesla Inc.',                          type: 'Stock' },
  { symbol: 'JPM',   name: 'JPMorgan Chase & Co.',                type: 'Stock' },
  { symbol: 'V',     name: 'Visa Inc.',                           type: 'Stock' },
  { symbol: 'MA',    name: 'Mastercard Inc.',                     type: 'Stock' },
  { symbol: 'XOM',   name: 'Exxon Mobil Corp.',                   type: 'Stock' },
  { symbol: 'JNJ',   name: 'Johnson & Johnson',                   type: 'Stock' },
  { symbol: 'UNH',   name: 'UnitedHealth Group Inc.',             type: 'Stock' },
  { symbol: 'PG',    name: 'Procter & Gamble Co.',                type: 'Stock' },
  { symbol: 'HD',    name: 'Home Depot Inc.',                     type: 'Stock' },
  { symbol: 'AVGO',  name: 'Broadcom Inc.',                       type: 'Stock' },
  { symbol: 'LLY',   name: 'Eli Lilly and Company',               type: 'Stock' },
  { symbol: 'MRK',   name: 'Merck & Co.',                        type: 'Stock' },
  { symbol: 'COST',  name: 'Costco Wholesale Corp.',              type: 'Stock' },
  { symbol: 'ABBV',  name: 'AbbVie Inc.',                         type: 'Stock' },
  { symbol: 'CVX',   name: 'Chevron Corp.',                       type: 'Stock' },
  { symbol: 'CRM',   name: 'Salesforce Inc.',                     type: 'Stock' },
  { symbol: 'NFLX',  name: 'Netflix Inc.',                        type: 'Stock' },
  { symbol: 'AMD',   name: 'Advanced Micro Devices Inc.',         type: 'Stock' },
  { symbol: 'INTC',  name: 'Intel Corp.',                         type: 'Stock' },
  { symbol: 'QCOM',  name: 'Qualcomm Inc.',                       type: 'Stock' },
  { symbol: 'TXN',   name: 'Texas Instruments Inc.',              type: 'Stock' },
  { symbol: 'MU',    name: 'Micron Technology Inc.',              type: 'Stock' },
  { symbol: 'AMAT',  name: 'Applied Materials Inc.',              type: 'Stock' },
  { symbol: 'LRCX',  name: 'Lam Research Corp.',                  type: 'Stock' },
  { symbol: 'ASML',  name: 'ASML Holding N.V.',                   type: 'Stock' },
  { symbol: 'ARM',   name: 'Arm Holdings plc',                    type: 'Stock' },
  { symbol: 'SMCI',  name: 'Super Micro Computer Inc.',           type: 'Stock' },
  { symbol: 'TSM',   name: 'Taiwan Semiconductor Mfg.',          type: 'Stock' },
  { symbol: 'ORCL',  name: 'Oracle Corp.',                        type: 'Stock' },
  { symbol: 'ADBE',  name: 'Adobe Inc.',                          type: 'Stock' },
  { symbol: 'NOW',   name: 'ServiceNow Inc.',                     type: 'Stock' },
  { symbol: 'INTU',  name: 'Intuit Inc.',                         type: 'Stock' },
  { symbol: 'T',     name: 'AT&T Inc.',                           type: 'Stock' },
  { symbol: 'VZ',    name: 'Verizon Communications Inc.',         type: 'Stock' },
  { symbol: 'CMCSA', name: 'Comcast Corp.',                       type: 'Stock' },
  { symbol: 'BAC',   name: 'Bank of America Corp.',               type: 'Stock' },
  { symbol: 'MS',    name: 'Morgan Stanley',                      type: 'Stock' },
  { symbol: 'GS',    name: 'Goldman Sachs Group Inc.',            type: 'Stock' },
  { symbol: 'WMT',   name: 'Walmart Inc.',                        type: 'Stock' },
  { symbol: 'DIS',   name: 'Walt Disney Co.',                     type: 'Stock' },
  { symbol: 'BA',    name: 'Boeing Co.',                          type: 'Stock' },
  { symbol: 'CAT',   name: 'Caterpillar Inc.',                    type: 'Stock' },
  { symbol: 'GE',    name: 'GE Aerospace',                        type: 'Stock' },
  { symbol: 'F',     name: 'Ford Motor Company',                  type: 'Stock' },
  { symbol: 'GM',    name: 'General Motors Co.',                  type: 'Stock' },
  { symbol: 'UBER',  name: 'Uber Technologies Inc.',              type: 'Stock' },
  { symbol: 'LYFT',  name: 'Lyft Inc.',                           type: 'Stock' },
  { symbol: 'COIN',  name: 'Coinbase Global Inc.',                type: 'Stock' },
  { symbol: 'HOOD',  name: 'Robinhood Markets Inc.',              type: 'Stock' },
  { symbol: 'PLTR',  name: 'Palantir Technologies Inc.',          type: 'Stock' },
  { symbol: 'AMC',   name: 'AMC Entertainment Holdings',          type: 'Stock' },
  { symbol: 'GME',   name: 'GameStop Corp.',                      type: 'Stock' },
  { symbol: 'SOFI',  name: 'SoFi Technologies Inc.',              type: 'Stock' },
  { symbol: 'RIVN',  name: 'Rivian Automotive Inc.',              type: 'Stock' },
  { symbol: 'LCID',  name: 'Lucid Group Inc.',                    type: 'Stock' },
  { symbol: 'NIO',   name: 'NIO Inc.',                            type: 'Stock' },
  { symbol: 'SNAP',  name: 'Snap Inc.',                           type: 'Stock' },
  { symbol: 'PINS',  name: 'Pinterest Inc.',                      type: 'Stock' },
  { symbol: 'RBLX',  name: 'Roblox Corp.',                        type: 'Stock' },
  { symbol: 'ABNB',  name: 'Airbnb Inc.',                         type: 'Stock' },
  { symbol: 'DASH',  name: 'DoorDash Inc.',                       type: 'Stock' },
  { symbol: 'SHOP',  name: 'Shopify Inc.',                        type: 'Stock' },
  { symbol: 'SQ',    name: 'Block Inc.',                          type: 'Stock' },
  { symbol: 'PYPL',  name: 'PayPal Holdings Inc.',                type: 'Stock' },
  { symbol: 'ROKU',  name: 'Roku Inc.',                           type: 'Stock' },
  { symbol: 'PTON',  name: 'Peloton Interactive Inc.',            type: 'Stock' },
  { symbol: 'MRNA',  name: 'Moderna Inc.',                        type: 'Stock' },
  { symbol: 'PFE',   name: 'Pfizer Inc.',                         type: 'Stock' },
  { symbol: 'BNTX',  name: 'BioNTech SE',                         type: 'Stock' },
  { symbol: 'KO',    name: 'Coca-Cola Company',                   type: 'Stock' },
  { symbol: 'PEP',   name: 'PepsiCo Inc.',                        type: 'Stock' },
  { symbol: 'MCD',   name: "McDonald's Corp.",                    type: 'Stock' },
  { symbol: 'SBUX',  name: 'Starbucks Corp.',                     type: 'Stock' },
  { symbol: 'NKE',   name: 'Nike Inc.',                           type: 'Stock' },
  { symbol: 'LULU',  name: 'Lululemon Athletica Inc.',            type: 'Stock' },
  { symbol: 'TGT',   name: 'Target Corp.',                        type: 'Stock' },
  { symbol: 'SPOT',  name: 'Spotify Technology S.A.',             type: 'Stock' },
  { symbol: 'BABA',  name: 'Alibaba Group Holding Ltd.',          type: 'Stock' },
  { symbol: 'MELI',  name: 'MercadoLibre Inc.',                   type: 'Stock' },
  { symbol: 'SE',    name: 'Sea Limited',                         type: 'Stock' },
  { symbol: 'MSTR',  name: 'MicroStrategy Inc.',                  type: 'Stock' },
  { symbol: 'APP',   name: 'AppLovin Corp.',                      type: 'Stock' },
  { symbol: 'NET',   name: 'Cloudflare Inc.',                     type: 'Stock' },
  { symbol: 'SNOW',  name: 'Snowflake Inc.',                      type: 'Stock' },
  { symbol: 'DDOG',  name: 'Datadog Inc.',                        type: 'Stock' },
  { symbol: 'CRWD',  name: 'CrowdStrike Holdings Inc.',           type: 'Stock' },
  { symbol: 'OKTA',  name: 'Okta Inc.',                           type: 'Stock' },
  { symbol: 'PATH',  name: 'UiPath Inc.',                         type: 'Stock' },
  { symbol: 'AI',    name: 'C3.ai Inc.',                          type: 'Stock' },
  { symbol: 'SOUN',  name: 'SoundHound AI Inc.',                  type: 'Stock' },
  { symbol: 'BBAI',  name: 'BigBear.ai Holdings',                 type: 'Stock' },
  { symbol: 'MARA',  name: 'Marathon Digital Holdings',           type: 'Stock' },
  { symbol: 'RIOT',  name: 'Riot Platforms Inc.',                 type: 'Stock' },
  { symbol: 'CLSK',  name: 'CleanSpark Inc.',                     type: 'Stock' },
  { symbol: 'HIMS',  name: 'Hims & Hers Health Inc.',             type: 'Stock' },
  { symbol: 'RDDT',  name: 'Reddit Inc.',                         type: 'Stock' },
  { symbol: 'CELH',  name: 'Celsius Holdings Inc.',               type: 'Stock' },
  { symbol: 'ON',    name: 'ON Semiconductor Corp.',              type: 'Stock' },
  { symbol: 'ENPH',  name: 'Enphase Energy Inc.',                 type: 'Stock' },
  { symbol: 'FSLR',  name: 'First Solar Inc.',                    type: 'Stock' },
  { symbol: 'PLUG',  name: 'Plug Power Inc.',                     type: 'Stock' },
  { symbol: 'WMT',   name: 'Walmart Inc.',                        type: 'Stock' },
  { symbol: 'IBM',   name: 'International Business Machines',     type: 'Stock' },
  { symbol: 'BYND',  name: 'Beyond Meat Inc.',                    type: 'Stock' },
  { symbol: 'ZS',    name: 'Zscaler Inc.',                        type: 'Stock' },

  // ── Popular ETFs ──
  { symbol: 'SPY',   name: 'SPDR S&P 500 ETF Trust',             type: 'ETF' },
  { symbol: 'QQQ',   name: 'Invesco QQQ Trust (Nasdaq 100)',      type: 'ETF' },
  { symbol: 'IWM',   name: 'iShares Russell 2000 ETF',            type: 'ETF' },
  { symbol: 'DIA',   name: 'SPDR Dow Jones Industrial Avg ETF',   type: 'ETF' },
  { symbol: 'GLD',   name: 'SPDR Gold Shares ETF',                type: 'ETF' },
  { symbol: 'IAU',   name: 'iShares Gold Trust ETF',              type: 'ETF' },
  { symbol: 'SLV',   name: 'iShares Silver Trust ETF',            type: 'ETF' },
  { symbol: 'USO',   name: 'United States Oil Fund ETF',          type: 'ETF' },
  { symbol: 'TLT',   name: 'iShares 20+ Year Treasury Bond ETF',  type: 'ETF' },
  { symbol: 'IEF',   name: 'iShares 7-10 Year Treasury Bond ETF', type: 'ETF' },
  { symbol: 'HYG',   name: 'iBoxx $ High Yield Corp Bond ETF',    type: 'ETF' },
  { symbol: 'XLE',   name: 'Energy Select Sector SPDR ETF',       type: 'ETF' },
  { symbol: 'XLF',   name: 'Financial Select Sector SPDR ETF',    type: 'ETF' },
  { symbol: 'XLK',   name: 'Technology Select Sector SPDR ETF',   type: 'ETF' },
  { symbol: 'XLV',   name: 'Health Care Select Sector SPDR ETF',  type: 'ETF' },
  { symbol: 'XLC',   name: 'Communication Services SPDR ETF',     type: 'ETF' },
  { symbol: 'XLY',   name: 'Consumer Discretionary SPDR ETF',     type: 'ETF' },
  { symbol: 'XLP',   name: 'Consumer Staples Select Sector ETF',  type: 'ETF' },
  { symbol: 'XLI',   name: 'Industrials Select Sector SPDR ETF',  type: 'ETF' },
  { symbol: 'XLB',   name: 'Materials Select Sector SPDR ETF',    type: 'ETF' },
  { symbol: 'XLU',   name: 'Utilities Select Sector SPDR ETF',    type: 'ETF' },
  { symbol: 'XLRE',  name: 'Real Estate Select Sector SPDR ETF',  type: 'ETF' },
  { symbol: 'ARKK',  name: 'ARK Innovation ETF',                  type: 'ETF' },
  { symbol: 'ARKG',  name: 'ARK Genomic Revolution ETF',          type: 'ETF' },
  { symbol: 'VTI',   name: 'Vanguard Total Stock Market ETF',     type: 'ETF' },
  { symbol: 'VOO',   name: 'Vanguard S&P 500 ETF',                type: 'ETF' },
  { symbol: 'VUG',   name: 'Vanguard Growth ETF',                 type: 'ETF' },
  { symbol: 'EFA',   name: 'iShares MSCI EAFE ETF',               type: 'ETF' },
  { symbol: 'EEM',   name: 'iShares MSCI Emerging Markets ETF',   type: 'ETF' },
  { symbol: 'SQQQ',  name: 'ProShares UltraPro Short QQQ (3x)',   type: 'ETF' },
  { symbol: 'TQQQ',  name: 'ProShares UltraPro QQQ (3x)',         type: 'ETF' },
  { symbol: 'SPXS',  name: 'Direxion S&P 500 Bear 3X ETF',       type: 'ETF' },
  { symbol: 'SPXL',  name: 'Direxion S&P 500 Bull 3X ETF',       type: 'ETF' },
  { symbol: 'UVXY',  name: 'ProShares Ultra VIX Short-Term ETF',  type: 'ETF' },
  { symbol: 'VXX',   name: 'iPath S&P 500 VIX Short-Term ETF',   type: 'ETF' },
  { symbol: 'UDOW',  name: 'ProShares UltraPro Dow30 (3x)',       type: 'ETF' },
  { symbol: 'SDOW',  name: 'ProShares UltraPro Short Dow30 (3x)', type: 'ETF' },
  { symbol: 'TNA',   name: 'Direxion Daily Small Cap Bull 3X ETF', type: 'ETF' },
  { symbol: 'TZA',   name: 'Direxion Daily Small Cap Bear 3X ETF', type: 'ETF' },
  { symbol: 'SOXX',  name: 'iShares Semiconductor ETF',           type: 'ETF' },
  { symbol: 'SOXL',  name: 'Direxion Daily Semiconductor Bull 3X', type: 'ETF' },
  { symbol: 'SOXS',  name: 'Direxion Daily Semiconductor Bear 3X', type: 'ETF' },
  { symbol: 'GDX',   name: 'VanEck Gold Miners ETF',              type: 'ETF' },
  { symbol: 'GDXJ',  name: 'VanEck Junior Gold Miners ETF',       type: 'ETF' },
  { symbol: 'NUGT',  name: 'Direxion Daily Gold Miners Bull 2X',  type: 'ETF' },
  { symbol: 'DUST',  name: 'Direxion Daily Gold Miners Bear 2X',  type: 'ETF' },
  { symbol: 'FAS',   name: 'Direxion Daily Financial Bull 3X ETF', type: 'ETF' },
  { symbol: 'FAZ',   name: 'Direxion Daily Financial Bear 3X ETF', type: 'ETF' },
  { symbol: 'LABU',  name: 'Direxion Daily S&P Biotech Bull 3X',  type: 'ETF' },
  { symbol: 'LABD',  name: 'Direxion Daily S&P Biotech Bear 3X',  type: 'ETF' },
  { symbol: 'TSLL',  name: 'Direxion Daily TSLA Bull 2X ETF',     type: 'ETF' },
  { symbol: 'NVDL',  name: 'GraniteShares 2x Long NVDA ETF',      type: 'ETF' },
  { symbol: 'MSTU',  name: 'T-Rex 2X Long MSTR Daily ETF',        type: 'ETF' },
  { symbol: 'IBIT',  name: 'iShares Bitcoin Trust ETF',            type: 'ETF' },
  { symbol: 'FBTC',  name: 'Fidelity Wise Origin Bitcoin ETF',     type: 'ETF' },
  { symbol: 'ETHA',  name: 'iShares Ethereum Trust ETF',           type: 'ETF' },

  // ── Futures (CME / CBOT / NYMEX) ──
  { symbol: 'ES',    name: 'S&P 500 E-mini Futures',              type: 'Futures' },
  { symbol: 'NQ',    name: 'Nasdaq 100 E-mini Futures',           type: 'Futures' },
  { symbol: 'YM',    name: 'Dow Jones E-mini Futures',            type: 'Futures' },
  { symbol: 'RTY',   name: 'Russell 2000 E-mini Futures',         type: 'Futures' },
  { symbol: 'MES',   name: 'Micro S&P 500 Futures',               type: 'Futures' },
  { symbol: 'MNQ',   name: 'Micro Nasdaq 100 Futures',            type: 'Futures' },
  { symbol: 'MYM',   name: 'Micro Dow Jones Futures',             type: 'Futures' },
  { symbol: 'M2K',   name: 'Micro Russell 2000 Futures',          type: 'Futures' },
  { symbol: 'CL',    name: 'Crude Oil (WTI) Futures',             type: 'Futures' },
  { symbol: 'NG',    name: 'Natural Gas Futures',                  type: 'Futures' },
  { symbol: 'GC',    name: 'Gold Futures',                         type: 'Futures' },
  { symbol: 'SI',    name: 'Silver Futures',                       type: 'Futures' },
  { symbol: 'HG',    name: 'Copper Futures',                       type: 'Futures' },
  { symbol: 'PL',    name: 'Platinum Futures',                     type: 'Futures' },
  { symbol: 'PA',    name: 'Palladium Futures',                    type: 'Futures' },
  { symbol: 'MGC',   name: 'Micro Gold Futures',                   type: 'Futures' },
  { symbol: 'SIL',   name: 'Micro Silver Futures',                 type: 'Futures' },
  { symbol: 'ZB',    name: 'US Treasury Bond Futures (30yr)',      type: 'Futures' },
  { symbol: 'ZN',    name: 'US Treasury Note Futures (10yr)',      type: 'Futures' },
  { symbol: 'ZF',    name: 'US Treasury Note Futures (5yr)',       type: 'Futures' },
  { symbol: 'ZT',    name: 'US Treasury Note Futures (2yr)',       type: 'Futures' },
  { symbol: '6E',    name: 'Euro FX Futures',                      type: 'Futures' },
  { symbol: '6J',    name: 'Japanese Yen Futures',                 type: 'Futures' },
  { symbol: '6B',    name: 'British Pound Futures',                type: 'Futures' },
  { symbol: '6C',    name: 'Canadian Dollar Futures',              type: 'Futures' },
  { symbol: '6A',    name: 'Australian Dollar Futures',            type: 'Futures' },
  { symbol: '6N',    name: 'New Zealand Dollar Futures',           type: 'Futures' },
  { symbol: '6S',    name: 'Swiss Franc Futures',                  type: 'Futures' },
  { symbol: 'ZC',    name: 'Corn Futures',                         type: 'Futures' },
  { symbol: 'ZW',    name: 'Wheat Futures',                        type: 'Futures' },
  { symbol: 'ZS',    name: 'Soybean Futures',                      type: 'Futures' },
  { symbol: 'LE',    name: 'Live Cattle Futures',                  type: 'Futures' },
  { symbol: 'HE',    name: 'Lean Hogs Futures',                    type: 'Futures' },
  { symbol: 'MBT',   name: 'Micro Bitcoin CME Futures',            type: 'Futures' },
  { symbol: 'MET',   name: 'Micro Ethereum CME Futures',           type: 'Futures' },

  // ── Crypto (spot) ──
  { symbol: 'BTC',   name: 'Bitcoin',                              type: 'Crypto' },
  { symbol: 'ETH',   name: 'Ethereum',                            type: 'Crypto' },
  { symbol: 'SOL',   name: 'Solana',                              type: 'Crypto' },
  { symbol: 'BNB',   name: 'BNB',                                 type: 'Crypto' },
  { symbol: 'XRP',   name: 'XRP',                                 type: 'Crypto' },
  { symbol: 'ADA',   name: 'Cardano',                             type: 'Crypto' },
  { symbol: 'DOGE',  name: 'Dogecoin',                            type: 'Crypto' },
  { symbol: 'AVAX',  name: 'Avalanche',                           type: 'Crypto' },
  { symbol: 'LINK',  name: 'Chainlink',                           type: 'Crypto' },
  { symbol: 'DOT',   name: 'Polkadot',                            type: 'Crypto' },
  { symbol: 'MATIC', name: 'Polygon',                             type: 'Crypto' },
  { symbol: 'UNI',   name: 'Uniswap',                             type: 'Crypto' },
  { symbol: 'LTC',   name: 'Litecoin',                            type: 'Crypto' },
  { symbol: 'BCH',   name: 'Bitcoin Cash',                        type: 'Crypto' },
  { symbol: 'ATOM',  name: 'Cosmos',                              type: 'Crypto' },
  { symbol: 'NEAR',  name: 'NEAR Protocol',                       type: 'Crypto' },
  { symbol: 'APT',   name: 'Aptos',                               type: 'Crypto' },
  { symbol: 'ARB',   name: 'Arbitrum',                            type: 'Crypto' },
  { symbol: 'OP',    name: 'Optimism',                            type: 'Crypto' },
  { symbol: 'INJ',   name: 'Injective',                           type: 'Crypto' },
  { symbol: 'SUI',   name: 'Sui',                                 type: 'Crypto' },
  { symbol: 'SEI',   name: 'Sei',                                 type: 'Crypto' },
  { symbol: 'TIA',   name: 'Celestia',                            type: 'Crypto' },
  { symbol: 'JUP',   name: 'Jupiter',                             type: 'Crypto' },
  { symbol: 'PEPE',  name: 'Pepe',                                type: 'Crypto' },
  { symbol: 'SHIB',  name: 'Shiba Inu',                           type: 'Crypto' },
  { symbol: 'WIF',   name: 'Dogwifhat',                           type: 'Crypto' },
  { symbol: 'BONK',  name: 'Bonk',                                type: 'Crypto' },
  { symbol: 'PYTH',  name: 'Pyth Network',                        type: 'Crypto' },
  { symbol: 'STRK',  name: 'Starknet',                            type: 'Crypto' },
  { symbol: 'ZK',    name: 'zkSync',                              type: 'Crypto' },
  { symbol: 'NOT',   name: 'Notcoin',                             type: 'Crypto' },
  { symbol: 'POPCAT',name: 'Popcat',                              type: 'Crypto' },
  { symbol: 'PNUT',  name: 'Peanut the Squirrel',                 type: 'Crypto' },
  { symbol: 'GOAT',  name: 'Goat of the Hill',                    type: 'Crypto' },
  { symbol: 'MOODENG',name:'Moo Deng',                            type: 'Crypto' },
  { symbol: 'ACT',   name: 'Act I: The AI Prophecy',              type: 'Crypto' },
  { symbol: 'TRUMP', name: 'TRUMP Meme Coin',                     type: 'Crypto' },
  { symbol: 'MELANIA',name:'MELANIA Meme Coin',                   type: 'Crypto' },

  // ── Forex ──
  { symbol: 'EUR/USD', name: 'Euro / US Dollar',                  type: 'Forex' },
  { symbol: 'GBP/USD', name: 'British Pound / US Dollar',         type: 'Forex' },
  { symbol: 'USD/JPY', name: 'US Dollar / Japanese Yen',          type: 'Forex' },
  { symbol: 'USD/CHF', name: 'US Dollar / Swiss Franc',           type: 'Forex' },
  { symbol: 'AUD/USD', name: 'Australian Dollar / US Dollar',     type: 'Forex' },
  { symbol: 'NZD/USD', name: 'New Zealand Dollar / US Dollar',    type: 'Forex' },
  { symbol: 'USD/CAD', name: 'US Dollar / Canadian Dollar',       type: 'Forex' },
  { symbol: 'EUR/GBP', name: 'Euro / British Pound',              type: 'Forex' },
  { symbol: 'EUR/JPY', name: 'Euro / Japanese Yen',               type: 'Forex' },
  { symbol: 'GBP/JPY', name: 'British Pound / Japanese Yen',      type: 'Forex' },
  { symbol: 'EUR/CHF', name: 'Euro / Swiss Franc',                type: 'Forex' },
  { symbol: 'AUD/JPY', name: 'Australian Dollar / Japanese Yen',  type: 'Forex' },
  { symbol: 'CAD/JPY', name: 'Canadian Dollar / Japanese Yen',    type: 'Forex' },
  { symbol: 'CHF/JPY', name: 'Swiss Franc / Japanese Yen',        type: 'Forex' },
  { symbol: 'GBP/CHF', name: 'British Pound / Swiss Franc',       type: 'Forex' },
  { symbol: 'AUD/CAD', name: 'Australian Dollar / Canadian Dollar',type: 'Forex' },
  { symbol: 'EUR/AUD', name: 'Euro / Australian Dollar',          type: 'Forex' },
  { symbol: 'EUR/CAD', name: 'Euro / Canadian Dollar',            type: 'Forex' },
  { symbol: 'GBP/AUD', name: 'British Pound / Australian Dollar', type: 'Forex' },
  { symbol: 'GBP/CAD', name: 'British Pound / Canadian Dollar',   type: 'Forex' },
  { symbol: 'USD/MXN', name: 'US Dollar / Mexican Peso',          type: 'Forex' },
  { symbol: 'USD/ZAR', name: 'US Dollar / South African Rand',    type: 'Forex' },
  { symbol: 'USD/SGD', name: 'US Dollar / Singapore Dollar',      type: 'Forex' },
  { symbol: 'USD/NOK', name: 'US Dollar / Norwegian Krone',       type: 'Forex' },
  { symbol: 'USD/TRY', name: 'US Dollar / Turkish Lira',          type: 'Forex' },
  { symbol: 'USD/CNH', name: 'US Dollar / Chinese Yuan (Offshore)',type: 'Forex' },
]

export function searchSymbols(query: string): SymbolEntry[] {
  if (!query || query.length === 0) return []
  const q = query.toUpperCase().trim()

  const symbolStarts   = SYMBOLS.filter(s => s.symbol.startsWith(q))
  const symbolContains = SYMBOLS.filter(s => !s.symbol.startsWith(q) && s.symbol.includes(q))
  const nameContains   = SYMBOLS.filter(s => !s.symbol.includes(q) && s.name.toUpperCase().includes(q))

  return [...symbolStarts, ...symbolContains, ...nameContains].slice(0, 8)
}
